<a href="https://colab.research.google.com/github/guzik1234/DataScienceCwiczenia/blob/main/Series%20%26%20DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

obiety typu series

In [5]:
s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3
b   -5
c    7
d    4
Name: sample, dtype: int64

In [3]:
s = pd.Series([3, -5, 7, 4])
s

0    3
1   -5
2    7
3    4
dtype: int64

In [7]:
s = pd.Series([3., -5, 7, 4], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3.0
b   -5.0
c    7.0
d    4.0
Name: sample, dtype: float64

In [8]:
import numpy as np
np.nan

nan

In [9]:
s = pd.Series([3., -np.nan, 7, 4], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3.0
b    NaN
c    7.0
d    4.0
Name: sample, dtype: float64

In [10]:
s = pd.Series(data=[True,False, False])
s

0     True
1    False
2    False
dtype: bool

In [26]:
s = pd.Series(data=np.arange(10,20), index= pd.date_range(start='20200101', periods=10))
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [21]:
list(s.index)

[Timestamp('2020-01-01 00:00:00'),
 Timestamp('2020-01-02 00:00:00'),
 Timestamp('2020-01-03 00:00:00'),
 Timestamp('2020-01-04 00:00:00'),
 Timestamp('2020-01-05 00:00:00'),
 Timestamp('2020-01-06 00:00:00'),
 Timestamp('2020-01-07 00:00:00'),
 Timestamp('2020-01-08 00:00:00'),
 Timestamp('2020-01-09 00:00:00'),
 Timestamp('2020-01-10 00:00:00')]

In [27]:
s.dtypes

dtype('int64')

In [23]:
s = pd.Series(data=['python', 'java', 'sql'], name='languages')
s

0    python
1      java
2       sql
Name: languages, dtype: object

In [17]:
type(s)

pandas.core.series.Series

In [18]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [24]:
s.values

array(['python', 'java', 'sql'], dtype=object)

In [25]:
s.dtypes

dtype('O')

In [28]:
s.shape

(10,)

In [43]:
price = pd.Series(data={'Apple': 200, 'CD Projekt': 60, 'Amazon': 1900, 'KGHM': np.nan})
price

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [30]:
price['CD Projekt']

np.int64(60)

In [33]:
price.iloc[1]

np.int64(60)

In [44]:
price.count()

np.int64(3)

In [46]:
price.value_counts(dropna=False)

200.0     1
60.0      1
1900.0    1
NaN       1
Name: count, dtype: int64

In [37]:
price.sum()

np.int64(2160)

In [38]:
price.min()

60

In [39]:
price.max()

1900

In [40]:
price.std()

1024.3046421841502

In [41]:
price.describe()

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [42]:
price.describe().T

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [48]:
price.nlargest(2)

Amazon    1900.0
Apple      200.0
dtype: float64

In [49]:
price.nsmallest(2)

CD Projekt     60.0
Apple         200.0
dtype: float64

In [50]:
price.rank()

Apple         2.0
CD Projekt    1.0
Amazon        3.0
KGHM          NaN
dtype: float64

In [51]:
price.sort_values()

CD Projekt      60.0
Apple          200.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [52]:
price.sort_values(ascending=False)

Amazon        1900.0
Apple          200.0
CD Projekt      60.0
KGHM             NaN
dtype: float64

In [53]:
price.apply(lambda x: x * 3.8)

Apple          760.0
CD Projekt     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

In [55]:
price_pln = price.apply(lambda x: x * 3.8)

In [56]:
price

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [58]:
df = pd.DataFrame(data=[12,12,32])
df

    0
0  12
1  12
2  32

In [59]:
df = pd.DataFrame(data=[12,12,32], index=['first', 'second', 'third'], columns=['col_1'])
df

        col_1
first      12
second     12
third      32

In [61]:
df = pd.DataFrame(data={'WIG20': ['PKN ORLEN', 'PKO BP'],
                        'mWIG40': ['Amica', 'Playway']})
df

       WIG20   mWIG40
0  PKN ORLEN    Amica
1     PKO BP  Playway

In [63]:
df = pd.DataFrame(data=[[10, 12, 13], [23, 12, 10]], index=['first', 'second'], columns=['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [64]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [65]:
df.index

Index(['first', 'second'], dtype='object')

In [66]:
df.values

array([[10, 12, 13],
       [23, 12, 10]])

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   2 non-null      int64
 1   col_2   2 non-null      int64
 2   col_3   2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes

In [68]:
df.describe()

           col_1  col_2     col_3
count   2.000000    2.0   2.00000
mean   16.500000   12.0  11.50000
std     9.192388    0.0   2.12132
min    10.000000   12.0  10.00000
25%    13.250000   12.0  10.75000
50%    16.500000   12.0  11.50000
75%    19.750000   12.0  12.25000
max    23.000000   12.0  13.00000

In [69]:
df.describe().T

       count  mean       std   min    25%   50%    75%   max
col_1    2.0  16.5  9.192388  10.0  13.25  16.5  19.75  23.0
col_2    2.0  12.0  0.000000  12.0  12.00  12.0  12.00  12.0
col_3    2.0  11.5  2.121320  10.0  10.75  11.5  12.25  13.0